// <auto-generated />
using System;
using GiftOfTheGivers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GiftOfTheGivers.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261003134722_AddDonationDonorDateIndex")]
    partial class AddDonationDonorDateIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GiftOfTheGivers.Data.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DonationId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Donations_UserId");

                    b.HasIndex("UserId", "DonationDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Donations_UserId_DonationDate");

                    b.ToTable("Donations", (string)null);
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.DonationAllocation", b =>
                {
                    b.Property<int>("DonationAllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationAllocationId"));

                    b.Property<DateTime>("AllocationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AmountAllocated")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<int>("ReliefOperationId")
                        .HasColumnType("int");

                    b.HasKey("DonationAllocationId");

                    b.HasIndex("DonationId");

                    b.HasIndex("ReliefOperationId");

                    b.ToTable("DonationAllocations", (string)null);
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.DonationSchedule", b =>
                {
                    b.Property<int>("DonationScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonationScheduleId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DonationScheduleId");

                    b.HasIndex("DonorId");

                    b.ToTable("DonationSchedules", (string)null);
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.ReliefOperation", b =>
                {
                    b.Property<int>("ReliefOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReliefOperationId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReliefRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReliefOperationId");

                    b.HasIndex("ReliefRequestId");

                    b.ToTable("ReliefOperations", (string)null);
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.ReliefRequest", b =>
                {
                    b.Property<int>("ReliefRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReliefRequestId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReliefRequestId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("ReliefRequests", (string)null);
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.TaxCertificate", b =>
                {
                    b.Property<int>("TaxCertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxCertificateId"));

                    b.Property<decimal>("CertificateAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TaxCertificateId");

                    b.HasIndex("DonationId");

                    b.ToTable("TaxCertificates", (string)null);
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.Volunteer", b =>
                {
                    b.Property<int>("VolunteerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteerId"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("VolunteerId");

                    b.HasIndex("UserId");

                    b.ToTable("Volunteers", (string)null);
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.VolunteerAssignment", b =>
                {
                    b.Property<int>("VolunteerAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteerAssignmentId"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReliefOperationId")
                        .HasColumnType("int");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("int");

                    b.HasKey("VolunteerAssignmentId");

                    b.HasIndex("ReliefOperationId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("VolunteerAssignments", (string)null);
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.AuditLog", b =>
                {
                    b.HasOne("GiftOfTheGivers.Data.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.Donation", b =>
                {
                    b.HasOne("GiftOfTheGivers.Data.User", "User")
                        .WithMany("Donations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.DonationAllocation", b =>
                {
                    b.HasOne("GiftOfTheGivers.Data.Donation", "Donation")
                        .WithMany("DonationAllocations")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GiftOfTheGivers.Data.ReliefOperation", "ReliefOperation")
                        .WithMany("DonationAllocations")
                        .HasForeignKey("ReliefOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("ReliefOperation");
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.DonationSchedule", b =>
                {
                    b.HasOne("GiftOfTheGivers.Data.User", "Donor")
                        .WithMany("DonationSchedules")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.ReliefOperation", b =>
                {
                    b.HasOne("GiftOfTheGivers.Data.ReliefRequest", "ReliefRequest")
                        .WithMany("ReliefOperations")
                        .HasForeignKey("ReliefRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReliefRequest");
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.ReliefRequest", b =>
                {
                    b.HasOne("GiftOfTheGivers.Data.User", "RequestedByUser")
                        .WithMany("ReliefRequests")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.TaxCertificate", b =>
                {
                    b.HasOne("GiftOfTheGivers.Data.Donation", "Donation")
                        .WithMany("TaxCertificates")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donation");
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.Volunteer", b =>
                {
                    b.HasOne("GiftOfTheGivers.Data.User", "User")
                        .WithMany("Volunteers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.VolunteerAssignment", b =>
                {
                    b.HasOne("GiftOfTheGivers.Data.ReliefOperation", "ReliefOperation")
                        .WithMany("VolunteerAssignments")
                        .HasForeignKey("ReliefOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GiftOfTheGivers.Data.Volunteer", "Volunteer")
                        .WithMany("VolunteerAssignments")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReliefOperation");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.Donation", b =>
                {
                    b.Navigation("DonationAllocations");

                    b.Navigation("TaxCertificates");
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.ReliefOperation", b =>
                {
                    b.Navigation("DonationAllocations");

                    b.Navigation("VolunteerAssignments");
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.ReliefRequest", b =>
                {
                    b.Navigation("ReliefOperations");
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("DonationSchedules");

                    b.Navigation("Donations");

                    b.Navigation("ReliefRequests");

                    b.Navigation("Volunteers");
                });

            modelBuilder.Entity("GiftOfTheGivers.Data.Volunteer", b =>
                {
                    b.Navigation("VolunteerAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
